name: topiary
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - xlrd
  - openpyxl
  - matplotlib
  - biopython
  - tqdm
  - toytree>3.0
  - ete4
  - pip
  - pip:
    - opentree
    - dendropy
