name: topiary
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python<3.14
  - pip
  - numpy
  - pandas
  - xlrd
  - openpyxl
  - matplotlib
  - biopython
  - tqdm
  - dendropy
  - toytree
  - blast>=2.2
  - muscle>=5.0
  - openmpi<5
  - mpi4py
  - sphinx
  - sphinx_rtd_theme
  - pydata-sphinx-theme
  - pip:
    - opentree
    - ete4
