name: topiary
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - numpy
  - pandas
  - xlrd
  - openpyxl
  - matplotlib
  - biopython
  - tqdm
  - dendropy
  - toytree
  - blast>=2.2
  - muscle>=5.0
  - openmpi
  - mpi4py
  - pip:
    - opentree
    - ete4
